# Generated by Django 4.1.4 on 2022-12-23 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='psychologist', serialize=False, to='users.user')),
                ('note', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='users.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('psychologist', 'patient'), name='unique_psychologist_patient'),
        ),
    ]
