# Generated by Django 4.1.4 on 2023-01-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.TextField(choices=[('Scheduled', 'Scheduled'), ('Started', 'Started'), ('Completed', 'Completed'), ('Referred', 'Referred')], default='Scheduled'),
        ),
    ]
